import React from 'react'
import './AdrCard.css'

const AdrCard = ({ 
  title, 
  number, 
  status = 'accepted', 
  content, 
  onDownload 
}) => {
  const handleDownload = () => {
    const markdownContent = `# ADR-${number}: ${title}

**Status:** ${status.toUpperCase()}

## Content
${content}

---
*Generated by Archie AI Assistant*
`
    
    const blob = new Blob([markdownContent], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `ADR-${number}-${title.toLowerCase().replace(/\s+/g, '-')}.md`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
    
    if (onDownload) {
      onDownload(number, title)
    }
  }

  return (
    <div className="adr-card">
      <div className="adr-header">
        <h3 className="adr-title">
          {title}
          <span className="adr-number">ADR-{number}</span>
        </h3>
      </div>
      
      <div className={`adr-status status-${status}`}>
        {status.toUpperCase()}
      </div>
      
      <div className="adr-content">
        {content}
      </div>
      
      <div className="adr-actions">
        <button 
          className="download-button"
          onClick={handleDownload}
          title="Download as Markdown"
        >
          <span className="download-icon">⬇</span>
          Download .md
        </button>
      </div>
    </div>
  )
}

export default AdrCard
